<script type="text/javascript">
    //<![CDATA[
    function DndInxmailSynchronizeSubscribers() {
        window.open("<?php echo $this->getCheckUrl() ?>");
        return false;
    }
    document.observe("dom:loaded", function() {
        // initially hide all containers for tab content
        $('inxmail_is_subscribed').invoke('hide');
    });
    //]]>
</script>

<?php //if ($this->isSynchronized()): ?>
    <div style="margin-bottom: 5px;">
        <input type="checkbox" id="inxmail_is_subscribed" name="inxmail_is_subscribed" checked />
        Bitte beachten Sie bei erneuter Ausführung der Migration, dass u.U. Empfänger angemeldet werden die Ihre Anmeldung noch nicht bestätigt haben bzw. aus Inxmail gelöscht wurden. Sie sollten diese Aktion nur einmalig je Liste ausführen. Danach werden Anmeldungen / Abmeldungen automatisch an Inxmail übertragen.
    </div>
<?php //endif; ?>
<?php echo $this->getButtonHtml() ?>